### ISSUE TITLE
Date and time classes

### ISSUE THREAD

**Issue by donmendelson** [FIXTradingCommunity/fix-orchestra-cpp#2]
Suggestion: does it makes sense to use Boost Date_Time classes (or other well-known) rather than invent our own?

**Comment by bgluzman** [comment]
Yes, I'll be doing this after I finish up with the other TODOs. It should be fairly straightforward to pack the attributes extracted in the date/time/datetime/period into a more standardized structure.

I'll create a few other issues as well to track the other tasks that need to be resolved.
